version: '3'

services:
  productRegistrationWeb:
    depends_on:
      - productRegistrationApi
    build:
      context: ../product-registration_client
      dockerfile: Dockerfile
    image: optimaltech-web:latest
    container_name: productRegistrationWeb
    restart: always
    ports:
      - "3000:3000"
    environment:
      NODE_ENV: development
      NEXT_PUBLIC_API_URL: ${NEXT_PUBLIC_API_URL}

  productRegistrationApi:
    depends_on:
      - db
    build: 
      context: ../product-registration_api
      dockerfile: Dockerfile
    image: optimaltech-api:latest
    container_name: productRegistrationApi
    restart: always
    ports:
      - "3002:3002"
    environment:
      - DB_HOST=${DB_HOST}
      - DB_PORT=${DB_PORT}
      - DB_NAME=${DB_NAME}
      - DB_USERNAME=${DB_USERNAME}
      - DB_PASSWORD=${DB_PASSWORD}
      - URL_CLIENT=${URL_CLIENT}

  db:
    image: postgres:14
    container_name: optimalTechDb
    restart: always
    ports:
      - ${DB_PORT}:${DB_PORT}
    environment:
      - POSTGRES_DB=${DB_NAME}
      - POSTGRES_USER=${DB_USERNAME}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
    volumes:
      - ./postgres:/var/lib/postgresql/data